---

 - hosts: web
   become: yes
   tasks:

   - name: CentOS Install zabbix-agent
     command: "{{ item }}"
     with_items:
     - rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm --replacepkgs
     - dnf clean all
     - dnf install zabbix-agent -y
     - systemctl stop zabbix-agent.service
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

   - name: Ubuntu Install zabbix-agent
     command: "{{ item }}"
     with_items:
     - wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
     - dpkg -i zabbix-release_5.0-1+focal_all.deb
     - apt update
     - apt install zabbix-agent -y
     - rm -rf zabbix-release_5.0-1+focal_all.deb
     - systemctl stop zabbix-agent.service
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: Replace config
     template:
       src: /etc/ansible/common/files/zabbix_agentd.conf
       dest: /etc/zabbix/zabbix_agentd.conf

   - name: zabbix-agent systemd
     systemd:
       name: zabbix-agent
       enabled: yes
       state: started
